### ISSUE TITLE
Feature request : add options to choose which keys to disable

### ISSUE THREAD

**Issue by Wronschien** [timmontague/youtube-disable-number-seek#10]
Hello, I really like this extension but I want to keep Home/End active.
It's been a few days before I understood this was not Youtube that changed something but rather this addon updated. So I'm using @tuurep's fork from now on (thanks for that !).
But I think a good idea would be to implement options to let user decide which keys to disable. Not necessarily every number key with its own checkbox but these could be grouped like "Number pad", "Top line", "Home/End". Maybe allow "0" to have its own setting though.
What do you think ?

**Comment by tuurep** [comment]
Thanks for the mention!

I agree with you and have had similar thoughts... but ultimately what I'm thinking is that if we were to make toggles for a few very specific key shortcuts, wouldn't it be best to actually add a toggle for *every single* YouTube key shortcut instead?

Here's a list, though I'm not sure if it's 100% complete, this is about it:

https://support.google.com/youtube/answer/7631406?hl=en

I myself would disable a couple of keys outside of number-seek keys, maybe `m` and `c`.

Been thinking about creating an addon like this, but probably leaving `Disable Numberseek Except 0` as is for those who only care about the number seek and want an extremely minimal addon.

As for the recent Home/End change in this repo, it's unfortunately one that depends entirely on keyboard layout and this is why I think having settings would make most sense :smile:

**Comment by timmontague** [comment]
Bummer, sorry I broke the behavior you relied on!

I like the idea of having settings for which keys are disabled. I'll see if I can do it sometime this week, but pull requests are welcome if you have experience writing extensions.

**Comment by Wronschien** [comment]
Don't be sorry it's not that big an annoyance :)

Well do it when you can of course, I don't think I know enough of development to help but I'm in no hurry.

Btw, @tuurep's idea of toggling every youtube shortcuts would be nice too, quite more work though.
But I don't understand what you mean about Home/End and keyboard layout ? I'm using an AZERTY keyboard and these keys are placed the same as on QWERTY, so they were blocked by version 1.3 . Are there other layouts that place these two keys somewhere else ?

**Comment by tuurep** [comment]
> But I don't understand what you mean about Home/End and keyboard layout ?

Ah, I mean like where they are physically on a keyboard can vary quite a bit

And the reason they were disabled in #8 was:

> I keep hitting the Home key on my keyboard, as it's near the top row where my volume buttons are... and thus I keep jumping to the start of the video.

But for me they are similar to this:

![image](https://github.com/timmontague/youtube-disable-number-seek/assets/15036238/ef088832-9fee-433f-82ed-36cc4c85eddc)

or this:

![image](https://github.com/timmontague/youtube-disable-number-seek/assets/15036238/ea9d07e7-e57f-427b-ba3a-6b959fc6e220)

depending which keyboard I'm using, and I don't hit them accidentally in either case.

> Btw, @tuurep's idea of toggling every youtube shortcuts would be nice too, quite more work though.

I think I'll make this, maybe in a couple weeks. I'll let you know if you're interested.

Also, if we add a `0` toggle on this repo, we don't need my fork anymore :D

**Comment by Wronschien** [comment]
Oh I see, thanks for the explanation.

Well I have no problem with the other shortcuts, but more customisation is good to have. So clearly don't do it for me, and I'll have a look when it's done.

**Comment by tuurep** [comment]
I tried to implement this today! Please review :)

**Comment by Wronschien** [comment]
Good news, but I don't know how to get the modified files on github to try out ?

**Comment by tuurep** [comment]
You can try this if you want:

*(Edit: removed link pointing to deleted file)*

To install from file, Manage Extensions -> Gear icon -> Install Add-on From File...

**Comment by Wronschien** [comment]
Well it doesn't seem to work quite right for now, by default all settings are unchecked and yet all keys are disabled, there is some kind of wrong initialisation.

And a setting change is ignored by any video page that's already open.
I think the problem is that settings are only fetched on page load, it may be best to get settings at each key press.
Or more simply indicate in the settings page that changes only apply on reload.

**Comment by tuurep** [comment]
It's intended to check the boxes on first open of the settings page. I'll try to see what's wrong.

Only applying on page load was intentional, fetching storage on every key press sounds excessive to me, but I'm not sure.

Should we:

* Fetch on every keypress
* Add small text on settings.html about when settings (re)apply

?

Oh yeah also I think I tried option 1 once, but since fetching storage is async, it would block key *first*, so to me it seemed more trouble than it's worth.

**Comment by Wronschien** [comment]
Alright, then option 2 should be enough.

**Comment by tuurep** [comment]
Is it working other than that?

If so, I'll look mainly into the first-time usage with the checkboxes and storage (they aren't right for me either when clearing the storage and opening settings again)

**Comment by Wronschien** [comment]
Yes I think the only problem left is on first time.

**Comment by tuurep** [comment]
Awesome, thanks

**Comment by tuurep** [comment]
Turns out there was just a small typo-ish mistake, fixed and feel free to test:

Updated xpi:
https://github.com/tuurep/files/blob/main/yt-disable-number-seek-dev-1.4.3.xpi

More things to consider:

* I'm only bumping the third number in the version so that AMO allows to upload new test versions, if we decide to merge, I'd propose it's `1.4`
* The toggle `disable 0` disables both numpad and top-row 0, and `disable numpad` concerns only numpad 1-9, please comment if we should make some changes to this logic :smile:

**Comment by Wronschien** [comment]
This seems quite alright to me, but I think a setting should allow the top row separately, currently it's always disabled.
It's fine that both "0" are (dis)allowed together, it would really be a niche category of users would would want one without the other.

**Comment by tuurep** [comment]
Good idea, I'll add that today.

> It's fine that both "0" are (dis)allowed together, it would really be a niche category of users would would want one without the other

Thanks, I had similar thoughts about this and it's probably the simplest choice.

**Comment by tuurep** [comment]
Ok done

xpi:
https://github.com/tuurep/files/blob/main/yt-disable-number-seek-dev-1.4.4.xpi

@timmontague we're most likely finished here :)

**Comment by Wronschien** [comment]
Yes, seems good to me

**Comment by timmontague** [comment]
Fixed in v1.4. Thanks for your help @tuurep and @Wronschien!

**Comment by tuurep** [comment]
Cool, thanks!

**Comment by Wronschien** [comment]
Great news, thank you !
