### ISSUE TITLE
not an issue.. just an idea

### ISSUE THREAD

**Issue by JinkerJinx** [timmontague/youtube-disable-number-seek#4]
prob my biggest annoyance with youtube is that the up/down/left/right keys function differently depending on what is selected.

using them may have you seeking, or altering the volume, or scrolling the screen etc.

unsure if this could be disabled, and replaced with fixed actions (left/right = seek,, up/down = vol  ?/? = scroll.

just to keep this simple addon simple;
i guess this idea is better suited to a some other addon, or one separate from this.

**Comment by timmontague** [comment]
Thanks for the idea, but I'd like to keep this extension simple.
