### ISSUE TITLE
[Bug] `Ctrl + Alt + 4` bypasses normal extension functionality

### ISSUE THREAD

**Issue by MiaTroy** [timmontague/youtube-disable-number-seek#5]
This extension does not stop `Ctrl + Alt + 4` from navigating to 40% of the way through the video
This only happens with the key combo, not any other numbers

Steps to reproduce:
1. Load a video on YouTube
2. Press the button combination `Ctrl + Alt + 4`

**Comment by tuurep** [comment]
I couldn't reproduce that. Curious, what OS and what type of device are you using?

**Comment by MiaTroy** [comment]
Windows 10 Professional, Desktop, Firefox Version 111.0.1 (64-bit)

**Comment by tuurep** [comment]
Interesting. I tried on my Windows 10 desktop and these combos will navigate to the respective %:

<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>2</kbd>
<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>3</kbd>
<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>4</kbd>
<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>5</kbd>
<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>7</kbd>
<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>8</kbd>
<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>9</kbd>
<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>0</kbd>

but not <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>1</kbd> and <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>6</kbd>

Note that this is regardless whether I have this addon installed or not.

On my (linux) laptop, none of these do anything.

**Comment by timmontague** [comment]
I am also unable to reproduce this. ctrl+alt+4 on my computer does not seek a youtube video. Even so, this extension should be able to intercept when '4' is pressed and stop youtube from seeking. If this is still happening for you, can you try opening youtube, opening the developer tools, going to the Console tab, and entering this:
```
function keyhandler(e) {
      console.log(e.code, e.key)
}
window.addEventListener('keydown', keyhandler, true);
```
Then try your ctrl+alt+4 keypress and send me the results?

**Comment by MiaTroy** [comment]
This is fixed as of the most recent commit

**Comment by MiaTroy** [comment]
This is fixed as of the most recent commit, thanks :)

**Comment by tuurep** [comment]
Oh, cool. Can confirm on my Windows machine it's fixed as well.

So this must've fixed it inadvertently:

https://github.com/timmontague/youtube-disable-number-seek/commit/9993db0daa0814ee5f186b2e7727eeb7f6c10efa
