### ISSUE TITLE
Feature request: disable Home/End keys

### ISSUE THREAD

**Issue by BSwitchblade88** [timmontague/youtube-disable-number-seek#8]
I keep hitting the Home key on my keyboard, as it's near the top row where my volume buttons are... and thus I keep jumping to the start of the video.

Is it a consideration to add these keys to the exclusion list? If not, any guidance on how to DIY it myself would be much appreciated!

**Comment by azomDev** [comment]
I create a pull request #9 which should fix this, not sure if this extension is still being somewhat active tho :P

**Comment by timmontague** [comment]
I'm here!
Thanks for the pull request! I'll upload a new version shortly.
